# Generated by Django 5.1.5 on 2025-02-10 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permitting", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="authorizer",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="foreman",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="issuer",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="loto_officer",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="safety_gatekeeper",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="task_responsible",
        ),
        migrations.AddField(
            model_name="appointment",
            name="person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointed_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="permitting.role",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="permit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="permitting.permit",
            ),
        ),
    ]
