# Generated by Django 5.1.5 on 2025-02-10 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permitting", "0002_remove_appointment_authorizer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfirmationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Confirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confirmed", models.BooleanField(blank=True, null=True)),
                (
                    "permit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmations",
                        to="permitting.permit",
                    ),
                ),
                (
                    "what",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permitting.confirmationevent",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="GeneralConfirmation",
        ),
    ]
