# Generated by Django 5.1.5 on 2025-03-11 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("permitting", "0003_confirmationevent_confirmation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dailyopenclose",
            old_name="declared_led_workers_in",
            new_name="confirmed_led_workers_in",
        ),
        migrations.RemoveField(
            model_name="dailyopenclose",
            name="declared_loto_in_place",
        ),
    ]
