# Generated by Django 5.1.3 on 2025-04-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("permitting", "0006_actionnotification_infonotification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actionnotification",
            name="related_url",
        ),
        migrations.RemoveField(
            model_name="infonotification",
            name="related_url",
        ),
    ]
