# Generated by Django 5.1.3 on 2025-04-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("permitting", "0007_remove_actionnotification_related_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="infonotification",
            name="permit",
        ),
        migrations.RemoveField(
            model_name="infonotification",
            name="user",
        ),
        migrations.DeleteModel(
            name="ActionNotification",
        ),
        migrations.DeleteModel(
            name="InfoNotification",
        ),
    ]
